export const media = {
  heroHome: "/media/hero-home.webp",
  heroFeatures: "/media/hero-features.webp",
  heroPricing: "/media/hero-pricing.webp",
  heroHow: "/media/hero-how.webp",
  heroUsecases: "/media/hero-usecases.webp",
  fragIngest: "/media/frag-ingest.webp",
  fragLaunch: "/media/frag-launch.webp",
  fragSession: "/media/frag-session.webp",
  fragAgent: "/media/frag-agent.webp",
  fragBilling: "/media/frag-billing.webp",
  fragWorkspace: "/media/frag-workspace.webp",
  fragSales: "/media/frag-sales.webp",
  fragFounders: "/media/frag-founders.webp",
  fragCs: "/media/frag-cs.webp",
  stepUpload: "/media/step-upload.webp",
  stepLaunch: "/media/step-launch.webp",
  stepPresent: "/media/step-present.webp",
  stepAnswer: "/media/step-answer.webp",
  avatar1: "/media/avatar-1.webp",
  avatar2: "/media/avatar-2.webp",
  avatar3: "/media/avatar-3.webp",
  avatar4: "/media/avatar-4.webp",
  avatar5: "/media/avatar-5.webp",
  avatar6: "/media/avatar-6.webp",
};
